import {
    PackageSearch,
    Tag,
    Truck,
    LayoutDashboard,
    UserRound,
    ShoppingCart,
    ShoppingBag,
    PackageCheck,
    CircleDollarSign,
    FileText,
    FileBox,
    Warehouse,
    Logs,
    File,
    Scale,
    CalendarClock,
    TrendingUp,
    BarChart2,
    Clock,
    RotateCcw,
    Trash2,
    Shield,
    ShieldCheck,
    UserCheck,
    History,
    Building2,
    ArrowLeftRight,
    CreditCard,
} from 'lucide-vue-next';

export const menuSections = [
    {
        label: 'Dashboard',
        collapsible: false,
        items: [
            {
                title: 'Dashboard',
                routeName: 'dashboard',
                icon: LayoutDashboard,
                roles: ['super_admin', 'admin', 'cashier', 'warehouse'],
            },
            {
                title: 'Langganan',
                routeName: 'subscription.index',
                activeRoute: 'subscription.*',
                icon: CreditCard,
                roles: ['super_admin', 'admin', 'cashier', 'warehouse'],
            },
            {
                title: 'User',
                routeName: 'users.index',
                activeRoute: 'users.*',
                icon: UserRound,
                roles: ['super_admin', 'admin'],
            },
            {
                title: 'POS (Kasir)',
                routeName: 'pos.index',
                activeRoute: 'pos.*',
                icon: ShoppingCart,
                roles: ['super_admin', 'admin', 'cashier'],
            },
        ],
    },
    {
        label: 'Manajemen Data',
        collapsible: true,
        items: [
            {
                title: 'Produk',
                routeName: 'product.index',
                activeRoute: 'product.*',
                icon: PackageSearch,
                roles: ['super_admin', 'admin', 'warehouse'],
            },
            {
                title: 'Kategori',
                routeName: 'category.index',
                activeRoute: 'category.*',
                icon: Tag,
                roles: ['super_admin', 'admin'],
            },
            {
                title: 'Satuan',
                routeName: 'unit.index',
                activeRoute: 'unit.*',
                icon: Scale,
                roles: ['super_admin', 'admin', 'warehouse'],
            },
            {
                title: 'Supplier',
                routeName: 'supplier.index',
                activeRoute: 'supplier.*',
                icon: Truck,
                roles: ['super_admin', 'admin', 'warehouse'],
            },
            {
                title: 'Gudang',
                routeName: 'warehouse.index',
                activeRoute: 'warehouse.*',
                icon: Building2,
                roles: ['super_admin', 'admin', 'warehouse'],
            },
            {
                title: 'Promo & Diskon',
                routeName: 'promotions.index',
                activeRoute: 'promotions.*',
                icon: Tag,
                roles: ['super_admin', 'admin'],
            },
        ],
    },
    {
        label: 'Data Transaksi dan Penjualan',
        collapsible: true,
        items: [
            {
                title: 'Pembelian',
                routeName: 'purchase.index',
                activeRoute: 'purchase.*',
                icon: PackageCheck,
                roles: ['super_admin', 'admin', 'warehouse'],
                planFeature: 'purchasing',
            },
            {
                title: 'Penjualan',
                routeName: 'sale.index',
                activeRoute: 'sale.*',
                icon: ShoppingBag,
                roles: ['super_admin', 'admin', 'cashier'],
            },
            {
                title: 'Retur Penjualan',
                routeName: 'sale-return.index',
                activeRoute: 'sale-return.*',
                icon: RotateCcw,
                roles: ['super_admin', 'admin', 'cashier'],
            },
            {
                title: 'Transaksi Midtrans',
                routeName: 'midtrans.index',
                activeRoute: 'midtrans.*',
                icon: CircleDollarSign,
                roles: ['super_admin', 'admin', 'cashier'],
            },
            {
                title: 'Manajemen Shift',
                routeName: 'shift.index',
                activeRoute: 'shift.*',
                icon: Clock,
                roles: ['super_admin', 'admin', 'cashier'],
            },
        ],
    },
    {
        label: 'Laporan',
        collapsible: true,
        items: [
            {
                title: 'Laporan Penjualan',
                routeName: 'reports.sale.index',
                activeRoute: 'reports.sale.*',
                icon: FileText,
                roles: ['super_admin', 'admin', 'cashier'],
            },
            {
                title: 'Laporan Pembelian',
                routeName: 'reports.purchase.index',
                activeRoute: 'reports.purchase.*',
                icon: FileBox,
                roles: ['super_admin', 'admin', 'warehouse'],
                planFeature: 'purchase_report',
            },
            {
                title: 'Laporan Stock',
                routeName: 'reports.stock.index',
                activeRoute: 'reports.stock.*',
                icon: Warehouse,
                roles: ['super_admin', 'admin', 'warehouse'],
                planFeature: 'stock_report',
            },
            {
                title: 'Laporan Kedaluwarsa',
                routeName: 'reports.expiry.index',
                activeRoute: 'reports.expiry.*',
                icon: CalendarClock,
                roles: ['super_admin', 'admin', 'warehouse'],
                planFeature: 'stock_report',
            },
            {
                title: 'Laporan Laba / Rugi',
                routeName: 'reports.profit-loss',
                activeRoute: 'reports.profit-loss',
                icon: TrendingUp,
                roles: ['super_admin', 'admin'],
                planFeature: 'profit_loss',
            },
            {
                title: 'Analisis Produk',
                routeName: 'reports.product-movement',
                activeRoute: 'reports.product-movement',
                icon: BarChart2,
                roles: ['super_admin', 'admin'],
            },
        ],
    },
    {
        label: 'Pengaturan Akses',
        collapsible: true,
        items: [
            {
                title: 'Permission',
                routeName: 'permissions.index',
                activeRoute: 'permissions.*',
                icon: Shield,
                roles: ['super_admin', 'admin'],
            },
            {
                title: 'Role Permission',
                routeName: 'role-permissions.index',
                activeRoute: 'role-permissions.*',
                icon: ShieldCheck,
                roles: ['super_admin', 'admin'],
            },
            {
                title: 'User Permission',
                routeName: 'user-permissions.index',
                activeRoute: 'user-permissions.*',
                icon: UserCheck,
                roles: ['super_admin', 'admin'],
            },
        ],
    },
    {
        label: 'Lainnya',
        collapsible: true,
        items: [
            {
                title: 'Stock Opname',
                routeName: 'stock-adjustment.index',
                activeRoute: 'stock-adjustment.*',
                icon: Scale,
                roles: ['super_admin', 'admin', 'warehouse'],
            },
            {
                title: 'Log Stock',
                routeName: 'log-stock.index',
                activeRoute: 'log-stock.*',
                icon: Logs,
                roles: ['super_admin', 'admin', 'warehouse'],
            },
            {
                title: 'Pemindahan Stok',
                routeName: 'stock-transfer.index',
                activeRoute: 'stock-transfer.*',
                icon: ArrowLeftRight,
                roles: ['super_admin', 'admin', 'warehouse'],
                planFeature: 'multi_warehouse',
            },
            {
                title: 'File Manager',
                routeName: 'file-manager.index',
                activeRoute: 'file-manager.*',
                icon: File,
                roles: ['super_admin', 'admin', 'cashier', 'warehouse'],
                planFeature: 'file_manager',
            },
            {
                title: 'Sampah',
                routeName: 'trash.index',
                activeRoute: 'trash.*',
                icon: Trash2,
                roles: ['super_admin', 'admin'],
            },
            {
                title: 'Activity Log',
                routeName: 'activity-logs.index',
                activeRoute: 'activity-logs.*',
                icon: History,
                permissions: ['view_activity_logs'],
                planFeature: 'activity_log',
            },
        ],
    },
];
