import {
    PackageSearch,
    Tag,
    Truck,
    LayoutDashboard,
    UserRound,
    ShoppingCart,
    ShoppingBag,
    PackageCheck,
    CircleDollarSign,
    FileText,
    FileBox,
    Warehouse,
    Logs,
    File,
    Scale,
    CalendarClock,
    TrendingUp,
    BarChart2,
    Clock,
    RotateCcw,
    ScrollText,
    Trash2,
} from 'lucide-vue-next';

export const menuSections = [
    {
        label: 'Dashboard',
        collapsible: false,
        items: [
            {
                title: 'Dashboard',
                routeName: 'dashboard',
                icon: LayoutDashboard,
                roles: ['admin', 'cashier', 'warehouse'],
            },
            {
                title: 'User',
                routeName: 'users.index',
                activeRoute: 'users.*',
                icon: UserRound,
                roles: ['admin'],
            },
            {
                title: 'POS (Kasir)',
                routeName: 'pos.index',
                activeRoute: 'pos.*',
                icon: ShoppingCart,
                roles: ['admin', 'cashier'],
            },
        ],
    },
    {
        label: 'Manajemen Data',
        collapsible: true,
        items: [
            {
                title: 'Produk',
                routeName: 'product.index',
                activeRoute: 'product.*',
                icon: PackageSearch,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'Kategori',
                routeName: 'category.index',
                activeRoute: 'category.*',
                icon: Tag,
                roles: ['admin'],
            },
            {
                title: 'Satuan',
                routeName: 'unit.index',
                activeRoute: 'unit.*',
                icon: Scale,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'Supplier',
                routeName: 'supplier.index',
                activeRoute: 'supplier.*',
                icon: Truck,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'Promo & Diskon',
                routeName: 'promotions.index',
                activeRoute: 'promotions.*',
                icon: Tag,
                roles: ['admin'],
            },
        ],
    },
    {
        label: 'Data Transaksi dan Penjualan',
        collapsible: true,
        items: [
            {
                title: 'Pembelian',
                routeName: 'purchase.index',
                activeRoute: 'purchase.*',
                icon: PackageCheck,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'Penjualan',
                routeName: 'sale.index',
                activeRoute: 'sale.*',
                icon: ShoppingBag,
                roles: ['admin', 'cashier'],
            },
            {
                title: 'Retur Penjualan',
                routeName: 'sale-return.index',
                activeRoute: 'sale-return.*',
                icon: RotateCcw,
                roles: ['admin', 'cashier'],
            },
            {
                title: 'Transaksi Midtrans',
                routeName: 'midtrans.index',
                activeRoute: 'midtrans.*',
                icon: CircleDollarSign,
                roles: ['admin', 'cashier'],
            },
            {
                title: 'Manajemen Shift',
                routeName: 'shift.index',
                activeRoute: 'shift.*',
                icon: Clock,
                roles: ['admin', 'cashier'],
            },
        ],
    },
    {
        label: 'Laporan',
        collapsible: true,
        items: [
            {
                title: 'Laporan Penjualan',
                routeName: 'reports.sale.index',
                activeRoute: 'reports.sale.*',
                icon: FileText,
                roles: ['admin', 'cashier'],
            },
            {
                title: 'Laporan Pembelian',
                routeName: 'reports.purchase.index',
                activeRoute: 'reports.purchase.*',
                icon: FileBox,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'Laporan Stock',
                routeName: 'reports.stock.index',
                activeRoute: 'reports.stock.*',
                icon: Warehouse,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'Laporan Kedaluwarsa',
                routeName: 'reports.expiry.index',
                activeRoute: 'reports.expiry.*',
                icon: CalendarClock,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'Laporan Laba / Rugi',
                routeName: 'reports.profit-loss',
                activeRoute: 'reports.profit-loss',
                icon: TrendingUp,
                roles: ['admin'],
            },
            {
                title: 'Analisis Produk',
                routeName: 'reports.product-movement',
                activeRoute: 'reports.product-movement',
                icon: BarChart2,
                roles: ['admin'],
            },
        ],
    },
    {
        label: 'Lainnya',
        collapsible: true,
        items: [
            {
                title: 'Stock Opname',
                routeName: 'stock-adjustment.index',
                activeRoute: 'stock-adjustment.*',
                icon: Scale,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'Log Stock',
                routeName: 'log-stock.index',
                activeRoute: 'log-stock.*',
                icon: Logs,
                roles: ['admin', 'warehouse'],
            },
            {
                title: 'File Manager',
                routeName: 'file-manager.index',
                activeRoute: 'file-manager.*',
                icon: File,
                roles: ['admin', 'cashier', 'warehouse'],
            },
            {
                title: 'Sampah',
                routeName: 'trash.index',
                activeRoute: 'trash.*',
                icon: Trash2,
                roles: ['admin'],
            },
            {
                title: 'Queue Worker Logs',
                routeName: 'queue-worker-logs.index',
                activeRoute: 'queue-worker-logs.*',
                icon: ScrollText,
                roles: ['admin'],
            },
        ],
    },
];
